### ISSUE TITLE
מובמיינט

### ISSUE THREAD

**Issue by Louiml** [or-agami/meme-generator-ca#1]
למחוק את הפונקציה של המובמיינט בקוד ג'אווה סקריפט משום שיש חבילה שהמוב עם העכבר יותר נוח וקל

import move-text //זה עם yarn

HTML:
<div id="move">
<button onClick="move()">Top Text</button> 
</div>
<script lang="typescript">
import move-text
function move() {
move-text.move()
}
</script>
CSS:
#move {
background-color: בצע של הרקע שיש;
}

**Comment by or-agami** [comment]
תודה על הערה, בגלל שזה קנבס אז אי אפשר לשלוט על הטקסט ככה, חייב 'לצייר' את הטקסט כל פעם מחדש עם המיקום הרצוי

Thank you for your comment, due to the use of canvas I can't control the text, the only way is to re-render the text on canvas with the new position
